### ISSUE TITLE
Hosting Javadoc on the github site

### ISSUE THREAD

**Issue by pgavigan** [sachag678/JLOAF#83]
I think it would be good if we posted the up to date javadoc on the github page. This may simplify the documentation needed in the wiki (the wiki could link to the javadoc when needed). I found a blog post that outlines how this might be done: https://vaadin.com/blog/-/blogs/host-your-javadoc-s-online-in-github

**Comment by sachag678** [comment]
Added javadoc at https://sachag678.github.io/JLOAF/.
